export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_LOCALITIES = "FETCH_LOCALITIES";
export const FETCH_LOCALIZATION_KEYS_PGR = "FETCH_LOCALIZATION_KEYS_PGR";
export const UPDATE_I18nStore_CITY_PGR = "UPDATE_I18nStore_CITY_PGR";
export const FETCH_LOCALITY_LOCALIZATION_KEYS_PGR =
  "FETCH_LOCALITY_LOCALIZATION_KEYS_PGR";
export const CREATE_LOCALITY_DROPDOWN = "CREATE_LOCALITY_DROPDOWN";
export const UPDATE_I18nStore_LOCALITY_PGR = "UPDATE_I18nStore_LOCALITY_PGR";
